name: date_n_time
description: "Dart Package for working with Dates without Times and/or Zones."
version: 1.0.8
repository: https://github.com/CoalBuster/date_n_time

environment:
  sdk: ^3.6.0

dependencies:
  intl: ">=0.19.0 <0.21.0"

dev_dependencies:
  test: ^1.25.12
  lints: ^5.1.1