name: date_n_time
description: "Dart Extension Package for working with Dates without Times."
version: 1.0.1
repository: https://github.com/CoalBuster/date_n_time

environment:
  sdk: ^3.5.1

dependencies:
  intl: ^0.19.0

dev_dependencies:
  test: ^1.25.7
  